# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hwb9RgMk9-xlTP8pnH7EK-F6V8MBsM7i
"""

import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Produce random data
np.random.seed(0)
points = 500
X = np.linspace(-3, 3, points)
y = np.sin(X) + np.random.uniform(-0.5, 0.5, points) # randomize y-values

#plt.scatter(X, y) # x-coord, y-coord

# Define our model
model = Sequential()
model.add(Dense(50, activation='sigmoid',input_dim=1))
model.add(Dense(30, activation='sigmoid')) # hidden layer
model.add(Dense(1)) # output

adam = Adam(lr=0.01)
'''
mse: Mean-squared error, 
'''
model.compile(loss='mse', optimizer=adam)
model.fit(X, y, epochs=50) # train model

# Show non-linear model that was trained to fit our data
predictions = model.predict(X)
plt.scatter(X, y)
plt.plot(X, predictions, 'ro') # plot model as a red line
plt.show()